# .circleci/config.yml
version: 2
jobs:
  test:
    macos:
      xcode: "9.2.0"
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
      # required to set the correct ruby version
      # see https://circleci.com/docs/2.0/testing-ios/#custom-ruby-versions
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 8 (11.2) [" || true
      - checkout
      - restore_cache:
          key: 1-top-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Restore Gems
          command: |
           bundle check --gemfile Gemfile || bundle install --gemfile Gemfile
      - save_cache:
          key: 1-top-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - "{{ $GEM_HOME }}"
      # Make sure that the output directory exists
      - run: mkdir $FL_OUTPUT_DIR
      - run: cd app && bundle exec fastlane test
      - run:
          name: Danger
          command: |
            bundle exec danger
            
  integration:
    macos:
      xcode: "9.2.0"
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run: bundle install
      - run: cd app && bundle exec fastlane develop
      - store_artifacts:
          path: "${FL_OUTPUT_DIR}/Project Name.ipa"
  sprint:
    macos:
      xcode: "9.2.0"
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run: bundle install
      - run: cd app && bundle exec fastlane sprint
      - store_artifacts:
          path: "${FL_OUTPUT_DIR}/Project Name.ipa"
  beta:
    macos:
      xcode: "9.2.0"
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run: bundle install
      - run: cd app && bundle exec fastlane beta
      - store_artifacts:
          path: "${FL_OUTPUT_DIR}/Project Name.ipa"

workflows:
  version: 2
  integration:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - integration:
          requires:
            - test
          filters:
            branches:
              only: develop
      - sprint:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /sprint-.*/
      - beta:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /beta-.*/
